backend:
  name: github
  repo: mgthantzin/the-plain-gatsby

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: posts
    label: Posts
    folder: src/pages/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }