backend:
  name: github
  repo: mgthantzin/the-plain-gatsby

media_folder: public
public_folder: public

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }